name: google/bert_uncased_L-2_H-128_A-2  #classifer
tokenizer: google/bert_uncased_L-2_H-128_A-2 # tokenizer to converrt raw text to numerical 
                                             # representation
